### PR TITLE
Change shader version from 130 to 120 to be compatible with MacOS

### PR DESCRIPTION
**Pull request by LionZXY**
**Background**
RIght now we can't run GTNH on apple silicon processor

**Changes**
- Change shader version from 130 to 120

More info:
https://github.com/Morpheus1101/Avaritia/pull/161

### CODE REVIEW

**Comment by Dream-Master** [comment]
Beside compatibility is there any downside or performance issue? @LionZXY

**Comment by LionZXY** [comment]
@Dream-Master No, there is no degradation in this change. Without it, GTNH simply will not run on the new macbooks on Apple Silicon.

**Comment by Connor-Colenso** [comment]
Never thought I'd see the day when Mac actually got proper rendering for Avaritia to work. Thanks.

**Review by eigenraven — APPROVED** [review]

**Comment by SrYthan** [comment]
I know it's not the right topic, I couldn't open an issue, however I would like to know about the word breaker bug that breaks bedrock, do you intend to fix this?

even disabling the word breaker in the config still breaks bedrock.
Screenshot_1

**Pull request merged**
